In [569]:
print("Customer 360 Analytics Project Started")

Customer 360 Analytics Project Started

In [570]:
import pandas as pd
import numpy as np

In [571]:
customers = pd.read_csv("Dataset/customers.csv")

orders = pd.read_csv("Dataset/orders.csv")

products = pd.read_csv("Dataset/products.csv")

In [572]:
customers.head()
orders.head()
products.head()

  product_id product_name category   cost
0       P001    Product_1     Home   1423
1       P002    Product_2   Sports  19834
2       P003    Product_3  Fashion  44697
3       P004    Product_4   Sports  12001
4       P005    Product_5   Beauty  42359

In [573]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)

Customers: (500, 6)
Orders: (5000, 8)
Products: (100, 4)

In [574]:
customers.info()
orders.info()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       500 non-null    object
 1   age               500 non-null    int64
 2   gender            500 non-null    object
 3   city              500 non-null    object
 4   customer_segment  500 non-null    object
 5   signup_date       500 non-null    object
dtypes: int64(1), object(5)
memory usage: 23.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5000 non-null   object
 1   customer_id     5000 non-null   object
 2   product_id      5000 non-null   object
 3   order_date      5000 non-null   object
 4   quantity        5000 non-null   int64
 5   unit_price      5000 non-null   int64
 6   revenue         5000 non-null   int64
 7   payment_method  5000 non-null   object
dtypes: int64(3), object(5)
memory usage: 312.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    object
 1   product_name  100 non-null    object
 2   category      100 non-null    object
 3   cost          100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.3+ KB

In [575]:
customers.head()
orders.head()
products.head()

  product_id product_name category   cost
0       P001    Product_1     Home   1423
1       P002    Product_2   Sports  19834
2       P003    Product_3  Fashion  44697
3       P004    Product_4   Sports  12001
4       P005    Product_5   Beauty  42359

In [576]:
print(customers.shape)
print(orders.shape)
print(products.shape)

(500, 6)
(5000, 8)
(100, 4)

In [577]:
customers.columns
orders.columns
products.columns

Index(['product_id', 'product_name', 'category', 'cost'], dtype='object')

In [578]:
customers.info()
orders.info()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       500 non-null    object
 1   age               500 non-null    int64
 2   gender            500 non-null    object
 3   city              500 non-null    object
 4   customer_segment  500 non-null    object
 5   signup_date       500 non-null    object
dtypes: int64(1), object(5)
memory usage: 23.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5000 non-null   object
 1   customer_id     5000 non-null   object
 2   product_id      5000 non-null   object
 3   order_date      5000 non-null   object
 4   quantity        5000 non-null   int64
 5   unit_price      5000 non-null   int64
 6   revenue         5000 non-null   int64
 7   payment_method  5000 non-null   object
dtypes: int64(3), object(5)
memory usage: 312.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    object
 1   product_name  100 non-null    object
 2   category      100 non-null    object
 3   cost          100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.3+ KB

In [579]:
customers.isnull().sum()
orders.isnull().sum()
products.isnull().sum()

product_id      0
product_name    0
category        0
cost            0
dtype: int64

In [580]:
print("Customer duplicates:", customers.duplicated().sum())
print("Order duplicates:", orders.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())

Customer duplicates: 0
Order duplicates: 0
Product duplicates: 0

In [581]:
customers = customers.drop_duplicates()

orders = orders.drop_duplicates()

products = products.drop_duplicates()

In [582]:
print("Customer duplicates:", customers.duplicated().sum())
print("Order duplicates:", orders.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())

Customer duplicates: 0
Order duplicates: 0
Product duplicates: 0

In [583]:
print(customers.isnull().sum())
print(orders.isnull().sum())
print(products.isnull().sum())

customer_id         0
age                 0
gender              0
city                0
customer_segment    0
signup_date         0
dtype: int64
order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
unit_price        0
revenue           0
payment_method    0
dtype: int64
product_id      0
product_name    0
category        0
cost            0
dtype: int64

In [584]:
orders.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking

In [585]:
orders['order_date'] = pd.to_datetime(
    orders['order_date']
)

In [586]:
sales = orders.merge(
    products,
    on="product_id",
    how="left"
)

In [587]:
sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,cost
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,48440
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,9375
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,9215
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,5023
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,25040

In [588]:
sales = sales.merge(
    customers,
    on="customer_id",
    how="left"
)

In [589]:
sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,cost,age,gender,city,customer_segment,signup_date
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,48440,42,Female,Pune,Regular,2024-03-21
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,9375,59,Male,Hyderabad,Budget,2024-09-16
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,9215,28,Female,Delhi,Budget,2024-05-14
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,5023,56,Male,Delhi,Premium,2024-05-20
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,25040,57,Female,Bangalore,Budget,2024-01-30

In [590]:
sales['profit'] = (
    sales['revenue']
    -
    (sales['cost'] * sales['quantity'])
)

In [591]:
sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,cost,age,gender,city,customer_segment,signup_date,profit
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,48440,42,Female,Pune,Regular,2024-03-21,-95745
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,9375,59,Male,Hyderabad,Budget,2024-09-16,37456
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,9215,28,Female,Delhi,Budget,2024-05-14,247185
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,5023,56,Male,Delhi,Premium,2024-05-20,18548
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,25040,57,Female,Bangalore,Budget,2024-01-30,64779

In [592]:
sales.shape

(5000, 17)

In [593]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   object
 1   customer_id       5000 non-null   object
 2   product_id        5000 non-null   object
 3   order_date        5000 non-null   datetime64[ns]
 4   quantity          5000 non-null   int64
 5   unit_price        5000 non-null   int64
 6   revenue           5000 non-null   int64
 7   payment_method    5000 non-null   object
 8   product_name      5000 non-null   object
 9   category          5000 non-null   object
 10  cost              5000 non-null   int64
 11  age               5000 non-null   int64
 12  gender            5000 non-null   object
 13  city              5000 non-null   object
 14  customer_segment  5000 non-null   object
 15  signup_date       5000 non-null   object
 16  profit            5000 non-null   int64
dtypes: datetime64[ns](1), int64(6), object(10)
memory usage: 664.2+ KB

In [594]:

import os

os.makedirs("Dataset/Cleaned", exist_ok=True)

sales.to_csv(
    "Dataset/Cleaned/customer_360_sales.csv",
    index=False
)

In [595]:
sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,cost,age,gender,city,customer_segment,signup_date,profit
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,48440,42,Female,Pune,Regular,2024-03-21,-95745
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,9375,59,Male,Hyderabad,Budget,2024-09-16,37456
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,9215,28,Female,Delhi,Budget,2024-05-14,247185
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,5023,56,Male,Delhi,Premium,2024-05-20,18548
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,25040,57,Female,Bangalore,Budget,2024-01-30,64779

In [596]:
total_revenue = sales['revenue'].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 456482544

In [597]:
total_profit = sales['profit'].sum()

print("Total Profit:", total_profit)

Total Profit: 69890708

In [598]:
total_orders = sales['order_id'].nunique()

print("Total Orders:", total_orders)

Total Orders: 5000

In [599]:
total_customers = sales['customer_id'].nunique()

print("Total Customers:", total_customers)

Total Customers: 500

In [600]:
average_order_value = total_revenue / total_orders

print("Average Order Value:", average_order_value)

Average Order Value: 91296.5088

In [601]:
sales['order_date'].max()

Timestamp('2024-12-31 00:00:00')

In [602]:
reference_date = sales['order_date'].max()

reference_date

Timestamp('2024-12-31 00:00:00')

In [603]:
rfm = sales.groupby('customer_id').agg({

    'order_date': lambda x: (reference_date - x.max()).days,

    'order_id': 'count',

    'revenue': 'sum'

})

In [604]:
rfm.columns = [
    'Recency',
    'Frequency',
    'Monetary'
]

In [605]:
rfm.head()

             Recency  Frequency  Monetary
customer_id
C0001            123          6    557684
C0002             61         16   1455046
C0003             61         12    856505
C0004              4         11    737491
C0005            108          7    724011

In [606]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency'],
    5,
    labels=[5,4,3,2,1]
)


rfm['F_Score'] = pd.qcut(
    rfm['Frequency'],
    5,
    labels=[1,2,3,4,5]
)


rfm['M_Score'] = pd.qcut(
    rfm['Monetary'],
    5,
    labels=[1,2,3,4,5]
)

In [607]:
rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int)
    +
    rfm['F_Score'].astype(int)
    +
    rfm['M_Score'].astype(int)
)

In [608]:
rfm.head()

             Recency  Frequency  Monetary R_Score F_Score M_Score  RFM_Score
customer_id
C0001            123          6    557684       1       1       1          3
C0002             61         16   1455046       1       5       5         11
C0003             61         12    856505       1       4       3          8
C0004              4         11    737491       5       3       2         10
C0005            108          7    724011       1       1       2          4

In [609]:
def customer_segment(score):

    if score >= 13:
        return "Champions"

    elif score >= 10:
        return "Loyal Customers"

    elif score >= 7:
        return "Potential Loyal"

    else:
        return "At Risk"


rfm['Segment'] = rfm['RFM_Score'].apply(customer_segment)

In [610]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
customer_id,,,,,,,,
C0001,123,6,557684,1,1,1,3,At Risk
C0002,61,16,1455046,1,5,5,11,Loyal Customers
C0003,61,12,856505,1,4,3,8,Potential Loyal
C0004,4,11,737491,5,3,2,10,Loyal Customers
C0005,108,7,724011,1,1,2,4,At Risk

In [611]:
rfm['Segment'].value_counts()

Segment
Potential Loyal    159
Loyal Customers    142
At Risk            132
Champions           67
Name: count, dtype: int64

In [612]:
customer_360 = sales.merge(
    rfm,
    on="customer_id",
    how="left"
)

In [613]:
customer_360.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,...,signup_date,profit,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,...,2024-03-21,-95745,13,18,1826916,4,5,5,14,Champions
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,...,2024-09-16,37456,12,8,807508,4,2,3,9,Potential Loyal
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,...,2024-05-14,247185,37,9,868990,2,2,3,7,Potential Loyal
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,...,2024-05-20,18548,36,9,727659,2,2,2,6,At Risk
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,...,2024-01-30,64779,4,14,2003374,5,5,5,15,Champions

In [614]:
customer_360.to_csv(
    "Dataset/Cleaned/customer_360_final.csv",
    index=False
)

In [615]:
customer_360['Segment'].value_counts()

Segment
Loyal Customers    1674
Potential Loyal    1446
Champions           981
At Risk             899
Name: count, dtype: int64

In [616]:
customer_360.groupby('Segment')['revenue'].sum()

Segment
At Risk             74689948
Champions           97278968
Loyal Customers    154020738
Potential Loyal    130492890
Name: revenue, dtype: int64

In [617]:
customer_360.groupby('Segment')['profit'].sum()

Segment
At Risk             5270136
Champions          19593882
Loyal Customers    27287575
Potential Loyal    17739115
Name: profit, dtype: int64

In [618]:
customer_360.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,...,signup_date,profit,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,...,2024-03-21,-95745,13,18,1826916,4,5,5,14,Champions
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,...,2024-09-16,37456,12,8,807508,4,2,3,9,Potential Loyal
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,...,2024-05-14,247185,37,9,868990,2,2,3,7,Potential Loyal
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,...,2024-05-20,18548,36,9,727659,2,2,2,6,At Risk
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,...,2024-01-30,64779,4,14,2003374,5,5,5,15,Champions

In [619]:
customer_360['Segment'].value_counts()

Segment
Loyal Customers    1674
Potential Loyal    1446
Champions           981
At Risk             899
Name: count, dtype: int64

In [620]:
import sys

!{sys.executable} -m pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\annus\appdata\roaming\python\python313\site-packages (9.7.0)

In [621]:
import sys

print(sys.executable)

print(sys.path)

c:\ProgramData\anaconda3\python.exe
['c:\\ProgramData\\anaconda3\\python313.zip', 'c:\\ProgramData\\anaconda3\\DLLs', 'c:\\ProgramData\\anaconda3\\Lib', 'c:\\ProgramData\\anaconda3', '', 'C:\\Users\\annus\\AppData\\Roaming\\Python\\Python313\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\win32\\lib', 'c:\\ProgramData\\anaconda3\\Lib\\site-packages\\Pythonwin']

In [622]:
import sys

!{sys.executable} -m pip install mysql-connector-python --force-reinstall

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
  Attempting uninstall: mysql-connector-python
    Found existing installation: mysql-connector-python 9.7.0
    Uninstalling mysql-connector-python-9.7.0:
      Successfully uninstalled mysql-connector-python-9.7.0
Successfully installed mysql-connector-python-9.7.0

In [623]:
import mysql.connector

print("MySQL connector working")

MySQL connector working

In [624]:
import mysql.connector

In [625]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="26092006",
    database="Customer360"
)

print("Database Connected Successfully")

Database Connected Successfully

In [626]:
cursor = connection.cursor()

print("Cursor Created")

Cursor Created

In [627]:
import os
print(os.listdir("Dataset"))

['Cleaned', 'customers.csv', 'orders.csv', 'products.csv', 'README.md.txt']

In [628]:
os.listdir("Dataset/Cleaned")

['customer_360_final.csv',
 'customer_360_sales.csv',
 'dim_customer.csv',
 'dim_product.csv',
 'fact_sales.csv']

In [629]:
import pandas as pd

customer_360 = pd.read_csv(
    "Dataset/Cleaned/customer_360_final.csv"
)

customer_360.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,payment_method,product_name,category,...,signup_date,profit,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,O00001,C0307,P099,2024-06-03,3,16525,49575,Card,Product_99,Sports,...,2024-03-21,-95745,13,18,1826916,4,5,5,14,Champions
1,O00002,C0339,P067,2024-06-02,2,28103,56206,Cash,Product_67,Beauty,...,2024-09-16,37456,12,8,807508,4,2,3,9,Potential Loyal
2,O00003,C0032,P072,2024-03-30,5,58652,293260,Net Banking,Product_72,Home,...,2024-05-14,247185,37,9,868990,2,2,3,7,Potential Loyal
3,O00004,C0285,P064,2024-11-25,1,23571,23571,Net Banking,Product_64,Beauty,...,2024-05-20,18548,36,9,727659,2,2,2,6,At Risk
4,O00005,C0403,P068,2024-08-01,3,46633,139899,Net Banking,Product_68,Beauty,...,2024-01-30,64779,4,14,2003374,5,5,5,15,Champions

In [630]:
customer_360.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'quantity',
       'unit_price', 'revenue', 'payment_method', 'product_name', 'category',
       'cost', 'age', 'gender', 'city', 'customer_segment', 'signup_date',
       'profit', 'Recency', 'Frequency', 'Monetary', 'R_Score', 'F_Score',
       'M_Score', 'RFM_Score', 'Segment'],
      dtype='object')

In [631]:
dim_customer = customer_360[
[
'customer_id',
'age',
'gender',
'city',
'customer_segment',
'signup_date',
'Segment',
'Recency',
'Frequency',
'Monetary',
'RFM_Score'
]
].drop_duplicates()

In [632]:
dim_customer.head()

,customer_id,age,gender,city,customer_segment,signup_date,Segment,Recency,Frequency,Monetary,RFM_Score
0,C0307,42,Female,Pune,Regular,2024-03-21,Champions,13,18,1826916,14
1,C0339,59,Male,Hyderabad,Budget,2024-09-16,Potential Loyal,12,8,807508,9
2,C0032,28,Female,Delhi,Budget,2024-05-14,Potential Loyal,37,9,868990,7
3,C0285,56,Male,Delhi,Premium,2024-05-20,At Risk,36,9,727659,6
4,C0403,57,Female,Bangalore,Budget,2024-01-30,Champions,4,14,2003374,15

In [633]:
dim_customer.to_csv(
"Dataset/Cleaned/dim_customer.csv",
index=False
)

In [634]:
dim_product = customer_360[
[
'product_id',
'product_name',
'category',
'cost'
]
].drop_duplicates()

In [635]:
dim_product.head()

  product_id product_name category   cost
0       P099   Product_99   Sports  48440
1       P067   Product_67   Beauty   9375
2       P072   Product_72     Home   9215
3       P064   Product_64   Beauty   5023
4       P068   Product_68   Beauty  25040

In [636]:
dim_product.to_csv(
"Dataset/Cleaned/dim_product.csv",
index=False
)

In [637]:
fact_sales = customer_360[
[
'order_id',
'customer_id',
'product_id',
'order_date',
'quantity',
'unit_price',
'revenue',
'profit',
'payment_method'
]
]

In [638]:
fact_sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,profit,payment_method
0,O00001,C0307,P099,2024-06-03,3,16525,49575,-95745,Card
1,O00002,C0339,P067,2024-06-02,2,28103,56206,37456,Cash
2,O00003,C0032,P072,2024-03-30,5,58652,293260,247185,Net Banking
3,O00004,C0285,P064,2024-11-25,1,23571,23571,18548,Net Banking
4,O00005,C0403,P068,2024-08-01,3,46633,139899,64779,Net Banking

In [639]:
fact_sales.to_csv(
"Dataset/Cleaned/fact_sales.csv",
index=False
)

In [640]:
import os
print(os.listdir("Dataset/Cleaned"))

['customer_360_final.csv', 'customer_360_sales.csv', 'dim_customer.csv', 'dim_product.csv', 'fact_sales.csv']

In [641]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="26092006",
    database="Customer360"
)

print("Connected")

Connected

In [642]:
cursor = connection.cursor()

In [643]:
import pandas as pd

dim_customer = pd.read_csv(
    "Dataset/Cleaned/dim_customer.csv"
)

dim_customer.head()

,customer_id,age,gender,city,customer_segment,signup_date,Segment,Recency,Frequency,Monetary,RFM_Score
0,C0307,42,Female,Pune,Regular,2024-03-21,Champions,13,18,1826916,14
1,C0339,59,Male,Hyderabad,Budget,2024-09-16,Potential Loyal,12,8,807508,9
2,C0032,28,Female,Delhi,Budget,2024-05-14,Potential Loyal,37,9,868990,7
3,C0285,56,Male,Delhi,Premium,2024-05-20,At Risk,36,9,727659,6
4,C0403,57,Female,Bangalore,Budget,2024-01-30,Champions,4,14,2003374,15

In [644]:
print(dim_customer.columns)

Index(['customer_id', 'age', 'gender', 'city', 'customer_segment',
       'signup_date', 'Segment', 'Recency', 'Frequency', 'Monetary',
       'RFM_Score'],
      dtype='object')

In [645]:
sql = """
INSERT INTO Dim_Customer (
customer_id, age, gender, city,
customer_segment, signup_date,
Segment, Recency, Frequency, Monetary, RFM_Score
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

In [646]:
import pandas as pd

sql = """
INSERT INTO dim_customer (
customer_id, age, gender, city,
segment, signup_date
)
VALUES (%s,%s,%s,%s,%s,%s)
"""

cols = [
"customer_id",
"age",
"gender",
"city",
"segment",
"signup_date"
]

# STEP: check missing columns
missing = [c for c in cols if c not in dim_customer.columns]
print("Missing columns:", missing)

# SAFE execution only if no missing columns
if len(missing) == 0:

    data = dim_customer[cols].where(pd.notnull(dim_customer[cols]), None).values.tolist()

    cursor.executemany(sql, data)
    connection.commit()

    print("dim_customer loaded successfully")

else:
    print("Fix column names first before inserting")

Missing columns: ['segment']
Fix column names first before inserting

In [647]:
dim_customer.rename(
    columns={
        "Segment": "segment"
    },
    inplace=True
)

In [648]:
dim_customer.columns

Index(['customer_id', 'age', 'gender', 'city', 'customer_segment',
       'signup_date', 'segment', 'Recency', 'Frequency', 'Monetary',
       'RFM_Score'],
      dtype='object')

In [649]:
import pandas as pd

dim_customer = pd.read_csv(
    "Dataset/Cleaned/dim_customer.csv"
)

dim_customer.shape

(500, 11)

In [650]:
sql = """
INSERT IGNORE INTO dim_customer(
customer_id,
age,
gender,
city,
customer_segment,
signup_date,
Segment,
Recency,
Frequency,
Monetary,
RFM_Score
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""


cursor.executemany(
    sql,
    dim_customer.values.tolist()
)

connection.commit()

print("dim_customer loaded successfully")

dim_customer loaded successfully

In [651]:
import pandas as pd

dim_product = pd.read_csv(
    "Dataset/Cleaned/dim_product.csv"
)

dim_product.head()

  product_id product_name category   cost
0       P099   Product_99   Sports  48440
1       P067   Product_67   Beauty   9375
2       P072   Product_72     Home   9215
3       P064   Product_64   Beauty   5023
4       P068   Product_68   Beauty  25040

In [652]:
sql = """
INSERT IGNORE INTO dim_product(
product_id,
product_name,
category,
cost
)
VALUES (%s,%s,%s,%s)
"""


cursor.executemany(
    sql,
    dim_product.values.tolist()
)

connection.commit()

print(cursor.rowcount, "products inserted")
print("dim_product completed")

100 products inserted
dim_product completed

In [653]:
fact_sales = pd.read_csv(
    "Dataset/Cleaned/fact_sales.csv"
)

fact_sales.head()

,order_id,customer_id,product_id,order_date,quantity,unit_price,revenue,profit,payment_method
0,O00001,C0307,P099,2024-06-03,3,16525,49575,-95745,Card
1,O00002,C0339,P067,2024-06-02,2,28103,56206,37456,Cash
2,O00003,C0032,P072,2024-03-30,5,58652,293260,247185,Net Banking
3,O00004,C0285,P064,2024-11-25,1,23571,23571,18548,Net Banking
4,O00005,C0403,P068,2024-08-01,3,46633,139899,64779,Net Banking

In [654]:
fact_sales.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'quantity',
       'unit_price', 'revenue', 'profit', 'payment_method'],
      dtype='object')

In [656]:
fact_sales.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'quantity',
       'unit_price', 'revenue', 'profit', 'payment_method'],
      dtype='object')

In [659]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="26092006",
    database="Customer360"
)

cursor = connection.cursor()

print("Connected")

Connected

In [660]:
sql = """
INSERT IGNORE INTO fact_sales(
order_id,
customer_id,
product_id,
order_date,
quantity,
unit_price,
revenue,
profit,
payment_method
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""


data = fact_sales.values.tolist()

batch_size = 500

for i in range(0, len(data), batch_size):

    batch = data[i:i + batch_size]

    cursor.executemany(
        sql,
        batch
    )

    connection.commit()

    print(i + len(batch), "rows processed")


print("fact_sales completed")

500 rows processed
1000 rows processed
1500 rows processed
2000 rows processed
2500 rows processed
3000 rows processed
3500 rows processed
4000 rows processed
4500 rows processed
5000 rows processed
fact_sales completed

In [661]:
cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table)

('dim_customer',)
('dim_product',)
('fact_sales',)